name: "deploy"
on:
  push:
    workflow_dispatch:
    branches:
      - main

permissions:
  contents: write

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-2019
    name: build ClickOnce artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: ''

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore app
        shell: powershell
        run: |
          nuget restore -PackagesDirectory packages

      - name: Create publish of app
        shell: powershell
        run: |
          $versionToSet = ${{ github.run_number }};
          msbuild "EigenbelegToolAlpha/Leno All In One.csproj" /t:Publish /p:Configuration=Release /p:PlatformTarget=x64 /p:Version=$versionToSet /p:ApplicationRevision=$versionToSet

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: leno-all-in-one-cd-build
          path: |
            EigenbelegToolAlpha/bin/Release/app.publish
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to server
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: leno-all-in-one-cd-build

      - name: Display structure of downloaded files
        shell: bash
        run: |
          ls -R

      - name: upload release
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: root
          server: 8745676.online-server.cloud
          port: 22
          local_path: './*'
          remote_path: '/var/www/download/app.publish'
          sftp_only: true
          password: 9&$$Xc_w#O

      - name: archive release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          tag: ${{ github.run_number }}
          commit: ${{ github.sha }}
